### ISSUE TITLE
Quest Error

### ISSUE THREAD

**Issue by luizoe** [snaity/dboserver#4]
Error on Quest System...
You take a quest and he try to send a GU_CHAR_TELEPORT after the quest takken

**Comment by snaity** [comment]
Lets check it out

**Comment by snaity** [comment]
Check, here is not trying to send a GU_CHAR_TELEPORT

https://drive.google.com/file/d/0B48BwAvk4lG_UWFiaWg5enRSbXc/view?usp=sharing

**Comment by luizoe** [comment]
Strange....maybe i commented when i maked the pull request.
Anyway i hope you got my skype msgs at all ^^

**Comment by snaity** [comment]
of course, but the problem i don't use often the skype, let me check

**Comment by luizoe** [comment]
Okay, i really apreciate if you do the thing i asked,
because i have a lot of stuff to add...
If have other way to keep the contact with you its better ^^
thanks
after your next reply u can close this "issue"
