### ISSUE TITLE
Bbcode problem with the client DBO 0.50

### ISSUE THREAD

**Issue by Katkat95** [snaity/dboserver#7]
Hello, after compiling the emulator (very good by the way) I downloaded the client 0.50 (AKCORE) until there any concerns about connecting to the same server for editing templates, music and other.
Only concerns the translation, I have concerns about some tags like this line:

DST_LOBBY_MUST_CHOICE_SERVER="[align = ""center""]Server Selection[br][br]Choose a server[br][br]You can't move Characters between servers[br]be careful.[br][br]choose a server" 

the Center tag does not work, I want to know if this is due to the version I use?
Regards.

**Comment by snaity** [comment]
Its a client related problem, because some UI parts of old client cannot parse tags

**Comment by Katkat95** [comment]
Hello Snaity, first thank you for your answer, is it possible to pass on higher client version 0.59 or as at the moment it is best to stay on a 0.50?

Best Regards

**Comment by snaity** [comment]
0.59 and 0.50 is same shit, 0.5x the x is just a revision

**Comment by snaity** [comment]
the only version possible to use is 0.90, but the current one is from netmarble dbo kr, and its uses web sso login to authenticate account, with that is impossible to use.
